// Seed data: heads of state and government for every country, plus prominent
// business, media, judicial, religious and international figures.
// Snapshot of office-holders as of mid-2026. Entries marked "verify" in the
// UNCERTAIN list below changed (or may have changed) around the snapshot date.
//
// Tuple: [name, position, country, party/organisation, region/city, lat, lng, birthYear, category, bio]

export type Category = 'world_leader' | 'politician' | 'business' | 'media' | 'judiciary' | 'religious' | 'international' | 'military' | 'other'
export type SeedLeader = [string, string, string, string | null, string, number, number, number | null, Category, string]

export const UNCERTAIN = [
  'Romuald Wadagni', 'Horta Inta-A', 'Michael Randrianirina', 'Hakainde Hichilema', 'Hassan Sheikh Mohamud',
  'Laura Fernández', 'Alix Didier Fils-Aimé', 'Delcy Rodríguez', 'Tarique Rahman', 'Mohammed Shia al-Sudani',
  'Min Aung Hlaing', 'Balendra Shah', 'Anutin Charnvirakul', 'Tô Lâm', 'Željko Komšić', 'Iliana Iotova',
  'Mette Frederiksen', 'Péter Magyar', 'Rob Jetten', 'Janez Janša', 'Ulf Kristersson', 'ʻAisake Eke',
  'Philip Davis', 'Nikol Pashinyan', 'Abiy Ahmed',
]

// Countries deliberately left out because the office changed after the snapshot
// and the holder could not be confirmed: Colombia (inaugurated Aug 2026), Peru (Jul 2026).
// The US Federal Reserve chair is also omitted for the same reason.

export const LEADERS: SeedLeader[] = [
  // ───────────── AFRICA ─────────────
  ['Abdelmadjid Tebboune', 'President', 'Algeria', 'Independent', 'Algiers', 36.75, 3.06, 1945, 'world_leader', 'President of Algeria since 2019, re-elected in 2024 after a career in the FLN-era civil service and as prime minister.'],
  ['João Lourenço', 'President', 'Angola', 'MPLA', 'Luanda', -8.84, 13.23, 1954, 'world_leader', 'President of Angola since 2017 and leader of the MPLA, the party that has governed since independence.'],
  ['Romuald Wadagni', 'President', 'Benin', 'Progressive Union for Renewal', 'Porto-Novo', 6.50, 2.60, 1976, 'world_leader', 'Former finance minister elected president in 2026 as the successor to Patrice Talon.'],
  ['Duma Boko', 'President', 'Botswana', 'Umbrella for Democratic Change', 'Gaborone', -24.65, 25.91, 1969, 'world_leader', 'Lawyer who ended nearly six decades of BDP rule when he won the 2024 election.'],
  ['Ibrahim Traoré', 'Transitional President', 'Burkina Faso', 'Military', 'Ouagadougou', 12.37, -1.52, 1988, 'world_leader', 'Army captain who seized power in a 2022 coup and leads the junta governing Burkina Faso.'],
  ['Évariste Ndayishimiye', 'President', 'Burundi', 'CNDD-FDD', 'Gitega', -3.43, 29.92, 1968, 'world_leader', 'President of Burundi since 2020, a former general and ruling-party secretary-general.'],
  ['Ulisses Correia e Silva', 'Prime Minister', 'Cabo Verde', 'Movement for Democracy', 'Praia', 14.93, -23.51, 1962, 'world_leader', 'Prime minister of Cabo Verde since 2016 and leader of the centre-right MpD.'],
  ['Paul Biya', 'President', 'Cameroon', 'CPDM', 'Yaoundé', 3.87, 11.52, 1933, 'world_leader', 'In power since 1982 and re-elected in 2025, making him the world\'s oldest serving head of state.'],
  ['Faustin-Archange Touadéra', 'President', 'Central African Republic', 'United Hearts Movement', 'Bangui', 4.39, 18.56, 1957, 'world_leader', 'President since 2016; a 2023 referendum removed term limits and he won a third term in 2025.'],
  ['Mahamat Idriss Déby', 'President', 'Chad', 'Patriotic Salvation Movement', 'N\'Djamena', 12.13, 15.06, 1984, 'world_leader', 'Took power in 2021 after his father was killed, then won a contested 2024 election.'],
  ['Azali Assoumani', 'President', 'Comoros', 'Convention for the Renewal of the Comoros', 'Moroni', -11.70, 43.26, 1959, 'world_leader', 'Former coup leader who returned via elections and has governed the Comoros since 2016.'],
  ['Félix Tshisekedi', 'President', 'Democratic Republic of the Congo', 'UDPS', 'Kinshasa', -4.32, 15.31, 1963, 'world_leader', 'President of the DRC since 2019, re-elected in 2023 amid conflict in the east.'],
  ['Denis Sassou Nguesso', 'President', 'Republic of the Congo', 'Congolese Party of Labour', 'Brazzaville', -4.27, 15.28, 1943, 'world_leader', 'Has ruled Congo-Brazzaville for most of the period since 1979, winning another term in 2026.'],
  ['Alassane Ouattara', 'President', 'Côte d\'Ivoire', 'RHDP', 'Yamoussoukro', 6.82, -5.28, 1942, 'world_leader', 'Former IMF official who has been president since 2011 and won a fourth term in 2025.'],
  ['Ismaïl Omar Guelleh', 'President', 'Djibouti', 'People\'s Rally for Progress', 'Djibouti', 11.59, 43.15, 1947, 'world_leader', 'President of Djibouti since 1999, re-elected in 2026 after term limits were loosened.'],
  ['Abdel Fattah el-Sisi', 'President', 'Egypt', 'Independent', 'Cairo', 30.04, 31.24, 1954, 'world_leader', 'Former army chief who took power in 2013 and has been president since 2014.'],
  ['Teodoro Obiang Nguema Mbasogo', 'President', 'Equatorial Guinea', 'PDGE', 'Malabo', 3.75, 8.78, 1942, 'world_leader', 'In power since a 1979 coup, the longest-serving president in the world.'],
  ['Isaias Afwerki', 'President', 'Eritrea', 'PFDJ', 'Asmara', 15.34, 38.93, 1946, 'world_leader', 'Eritrea\'s only president since independence in 1993; no national election has ever been held.'],
  ['Mswati III', 'King', 'Eswatini', 'Monarchy', 'Mbabane', -26.31, 31.14, 1968, 'world_leader', 'Absolute monarch of Eswatini since 1986.'],
  ['Abiy Ahmed', 'Prime Minister', 'Ethiopia', 'Prosperity Party', 'Addis Ababa', 9.03, 38.74, 1976, 'world_leader', 'Nobel Peace laureate turned wartime prime minister, in office since 2018.'],
  ['Brice Oligui Nguema', 'President', 'Gabon', 'Union of Builders', 'Libreville', 0.42, 9.47, 1975, 'world_leader', 'General who led the 2023 coup and was elected president in 2025.'],
  ['Adama Barrow', 'President', 'Gambia', 'National People\'s Party', 'Banjul', 13.45, -16.58, 1965, 'world_leader', 'President of the Gambia since 2017 after unseating Yahya Jammeh.'],
  ['John Mahama', 'President', 'Ghana', 'National Democratic Congress', 'Accra', 5.60, -0.19, 1958, 'world_leader', 'Returned to the presidency in 2025 after a landslide win, having previously served 2012–2017.'],
  ['Mamadi Doumbouya', 'President', 'Guinea', 'Independent', 'Conakry', 9.64, -13.58, 1980, 'world_leader', 'Special-forces colonel who seized power in 2021 and was elected president in 2025.'],
  ['Horta Inta-A', 'Transitional President', 'Guinea-Bissau', 'Military', 'Bissau', 11.86, -15.60, null, 'world_leader', 'General installed as transitional president after the November 2025 coup.'],
  ['William Ruto', 'President', 'Kenya', 'United Democratic Alliance', 'Nairobi', -1.29, 36.82, 1966, 'world_leader', 'President of Kenya since 2022, facing sustained youth-led protests over taxes and policing.'],
  ['Sam Matekane', 'Prime Minister', 'Lesotho', 'Revolution for Prosperity', 'Maseru', -29.31, 27.48, 1958, 'world_leader', 'Diamond magnate who became prime minister in 2022 months after founding his party.'],
  ['Joseph Boakai', 'President', 'Liberia', 'Unity Party', 'Monrovia', 6.30, -10.80, 1944, 'world_leader', 'Veteran politician who defeated George Weah to become president in 2024.'],
  ['Abdul Hamid Dbeibeh', 'Prime Minister', 'Libya', 'Government of National Unity', 'Tripoli', 32.89, 13.19, 1958, 'world_leader', 'Interim prime minister in Tripoli since 2021 in a country still split between rival governments.'],
  ['Michael Randrianirina', 'President', 'Madagascar', 'Military', 'Antananarivo', -18.88, 47.51, 1974, 'world_leader', 'Colonel who took power after the October 2025 uprising forced out Andry Rajoelina.'],
  ['Peter Mutharika', 'President', 'Malawi', 'Democratic Progressive Party', 'Lilongwe', -13.96, 33.77, 1940, 'world_leader', 'Returned to office in 2025 after defeating Lazarus Chakwera; previously president 2014–2020.'],
  ['Assimi Goïta', 'Transitional President', 'Mali', 'Military', 'Bamako', 12.64, -8.00, 1983, 'world_leader', 'Colonel who led two coups and was granted a renewable five-year mandate without elections in 2025.'],
  ['Mohamed Ould Ghazouani', 'President', 'Mauritania', 'El Insaf', 'Nouakchott', 18.09, -15.98, 1956, 'world_leader', 'Former general, president since 2019 and re-elected in 2024.'],
  ['Navin Ramgoolam', 'Prime Minister', 'Mauritius', 'Labour Party', 'Port Louis', -20.16, 57.50, 1947, 'world_leader', 'Returned as prime minister in 2024 for a third stint leading Mauritius.'],
  ['Mohammed VI', 'King', 'Morocco', 'Monarchy', 'Rabat', 34.02, -6.84, 1963, 'world_leader', 'King of Morocco since 1999 with sweeping executive and religious authority.'],
  ['Aziz Akhannouch', 'Prime Minister', 'Morocco', 'National Rally of Independents', 'Rabat', 34.02, -6.84, 1961, 'world_leader', 'Billionaire businessman serving as prime minister of Morocco since 2021.'],
  ['Daniel Chapo', 'President', 'Mozambique', 'FRELIMO', 'Maputo', -25.97, 32.57, 1977, 'world_leader', 'Took office in 2025 after a disputed election that triggered months of deadly protests.'],
  ['Netumbo Nandi-Ndaitwah', 'President', 'Namibia', 'SWAPO', 'Windhoek', -22.56, 17.08, 1952, 'world_leader', 'Namibia\'s first female president, in office since 2025.'],
  ['Abdourahamane Tiani', 'President', 'Niger', 'Military', 'Niamey', 13.51, 2.11, 1964, 'world_leader', 'Presidential guard commander who took power in the 2023 coup.'],
  ['Bola Tinubu', 'President', 'Nigeria', 'All Progressives Congress', 'Abuja', 9.06, 7.49, 1952, 'world_leader', 'President of Nigeria since 2023; former governor of Lagos State.'],
  ['Paul Kagame', 'President', 'Rwanda', 'Rwandan Patriotic Front', 'Kigali', -1.94, 30.06, 1957, 'world_leader', 'Has led Rwanda since 1994 and won a fourth term in 2024 with over 99% of the vote.'],
  ['Carlos Vila Nova', 'President', 'São Tomé and Príncipe', 'Independent Democratic Action', 'São Tomé', 0.34, 6.73, 1959, 'world_leader', 'President of São Tomé and Príncipe since 2021.'],
  ['Bassirou Diomaye Faye', 'President', 'Senegal', 'PASTEF', 'Dakar', 14.69, -17.44, 1980, 'world_leader', 'Elected in 2024 days after his release from prison, Africa\'s youngest elected president.'],
  ['Ousmane Sonko', 'Prime Minister', 'Senegal', 'PASTEF', 'Dakar', 14.69, -17.44, 1974, 'world_leader', 'Opposition firebrand barred from the 2024 race who became prime minister under his ally Faye.'],
  ['Patrick Herminie', 'President', 'Seychelles', 'United Seychelles', 'Victoria', -4.62, 55.45, 1963, 'world_leader', 'Former speaker who won the 2025 presidential runoff.'],
  ['Julius Maada Bio', 'President', 'Sierra Leone', 'SLPP', 'Freetown', 8.48, -13.23, 1964, 'world_leader', 'President of Sierra Leone since 2018 and current ECOWAS chair.'],
  ['Hassan Sheikh Mohamud', 'President', 'Somalia', 'Union for Peace and Development', 'Mogadishu', 2.05, 45.32, 1955, 'world_leader', 'President of Somalia since 2022; previously held the office 2012–2017.'],
  ['Cyril Ramaphosa', 'President', 'South Africa', 'African National Congress', 'Pretoria', -25.75, 28.19, 1952, 'world_leader', 'President since 2018, now leading a coalition after the ANC lost its majority in 2024.'],
  ['Salva Kiir', 'President', 'South Sudan', 'SPLM', 'Juba', 4.86, 31.57, 1951, 'world_leader', 'South Sudan\'s only president since independence in 2011; elections repeatedly postponed.'],
  ['Abdel Fattah al-Burhan', 'Chairman of the Sovereignty Council', 'Sudan', 'Military', 'Khartoum', 15.50, 32.56, 1960, 'world_leader', 'Army chief leading one side of Sudan\'s civil war against the RSF.'],
  ['Samia Suluhu Hassan', 'President', 'Tanzania', 'Chama Cha Mapinduzi', 'Dodoma', -6.16, 35.75, 1960, 'world_leader', 'Tanzania\'s first female president, re-elected in 2025 in a vote marred by an opposition crackdown.'],
  ['Faure Gnassingbé', 'President of the Council of Ministers', 'Togo', 'UNIR', 'Lomé', 6.13, 1.22, 1966, 'world_leader', 'Has led Togo since 2005; a 2024 constitutional change moved him to a term-unlimited post.'],
  ['Kais Saied', 'President', 'Tunisia', 'Independent', 'Tunis', 36.81, 10.18, 1958, 'world_leader', 'Law professor elected in 2019 who suspended parliament in 2021 and rules by decree.'],
  ['Yoweri Museveni', 'President', 'Uganda', 'National Resistance Movement', 'Kampala', 0.35, 32.58, 1944, 'world_leader', 'In power since 1986 and re-elected for a seventh term in January 2026.'],
  ['Hakainde Hichilema', 'President', 'Zambia', 'United Party for National Development', 'Lusaka', -15.39, 28.32, 1962, 'world_leader', 'Businessman who won in 2021 on his sixth attempt; faced re-election in August 2026.'],
  ['Emmerson Mnangagwa', 'President', 'Zimbabwe', 'ZANU-PF', 'Harare', -17.83, 31.05, 1942, 'world_leader', 'Replaced Robert Mugabe in 2017; allies are pushing to extend his rule beyond 2028.'],

  // ───────────── AMERICAS ─────────────
  ['Gaston Browne', 'Prime Minister', 'Antigua and Barbuda', 'Antigua Labour Party', 'St. John\'s', 17.12, -61.85, 1967, 'world_leader', 'Prime minister since 2014.'],
  ['Javier Milei', 'President', 'Argentina', 'La Libertad Avanza', 'Buenos Aires', -34.60, -58.38, 1970, 'world_leader', 'Libertarian economist elected in 2023 on a chainsaw-austerity platform.'],
  ['Philip Davis', 'Prime Minister', 'Bahamas', 'Progressive Liberal Party', 'Nassau', 25.05, -77.34, 1951, 'world_leader', 'Prime minister of the Bahamas since 2021.'],
  ['Mia Mottley', 'Prime Minister', 'Barbados', 'Barbados Labour Party', 'Bridgetown', 13.10, -59.62, 1965, 'world_leader', 'Prime minister since 2018; led Barbados to become a republic in 2021.'],
  ['John Briceño', 'Prime Minister', 'Belize', 'People\'s United Party', 'Belmopan', 17.25, -88.77, 1960, 'world_leader', 'Prime minister since 2020, re-elected in 2025.'],
  ['Rodrigo Paz', 'President', 'Bolivia', 'Christian Democratic Party', 'La Paz', -16.50, -68.15, 1967, 'world_leader', 'Senator who won the 2025 runoff, ending two decades of MAS rule.'],
  ['Luiz Inácio Lula da Silva', 'President', 'Brazil', 'Workers\' Party', 'Brasília', -15.79, -47.88, 1945, 'world_leader', 'Serving a third non-consecutive term since 2023 after defeating Jair Bolsonaro.'],
  ['José Antonio Kast', 'President', 'Chile', 'Republican Party', 'Santiago', -33.45, -70.67, 1966, 'world_leader', 'Hard-right lawyer who won the 2025 runoff and took office in March 2026.'],
  ['Laura Fernández', 'President', 'Costa Rica', 'Pueblo Soberano', 'San José', 9.93, -84.08, 1989, 'world_leader', 'Rodrigo Chaves\'s former chief of staff, elected president in 2026.'],
  ['Miguel Díaz-Canel', 'President', 'Cuba', 'Communist Party of Cuba', 'Havana', 23.11, -82.37, 1960, 'world_leader', 'First non-Castro to lead Cuba since the revolution; president since 2019.'],
  ['Roosevelt Skerrit', 'Prime Minister', 'Dominica', 'Dominica Labour Party', 'Roseau', 15.30, -61.39, 1972, 'world_leader', 'Prime minister since 2004, the longest-serving leader in the Caribbean.'],
  ['Luis Abinader', 'President', 'Dominican Republic', 'Modern Revolutionary Party', 'Santo Domingo', 18.49, -69.93, 1967, 'world_leader', 'President since 2020, re-elected in 2024.'],
  ['Daniel Noboa', 'President', 'Ecuador', 'National Democratic Action', 'Quito', -0.18, -78.47, 1987, 'world_leader', 'Banana-fortune heir elected in 2023 and re-elected in 2025 amid a gang-violence emergency.'],
  ['Nayib Bukele', 'President', 'El Salvador', 'Nuevas Ideas', 'San Salvador', 13.69, -89.19, 1981, 'world_leader', 'Self-styled "world\'s coolest dictator", re-elected in 2024 on a mass-incarceration security policy.'],
  ['Dickon Mitchell', 'Prime Minister', 'Grenada', 'National Democratic Congress', 'St. George\'s', 12.06, -61.75, 1978, 'world_leader', 'Prime minister since 2022.'],
  ['Bernardo Arévalo', 'President', 'Guatemala', 'Movimiento Semilla', 'Guatemala City', 14.63, -90.51, 1958, 'world_leader', 'Anti-corruption sociologist who took office in 2024 despite attempts to block him.'],
  ['Irfaan Ali', 'President', 'Guyana', 'People\'s Progressive Party/Civic', 'Georgetown', 6.80, -58.16, 1980, 'world_leader', 'President since 2020, re-elected in 2025, presiding over an oil boom.'],
  ['Alix Didier Fils-Aimé', 'Prime Minister', 'Haiti', 'Independent', 'Port-au-Prince', 18.54, -72.34, 1973, 'world_leader', 'Businessman appointed prime minister in late 2024 as gangs control most of the capital.'],
  ['Nasry Asfura', 'President', 'Honduras', 'National Party', 'Tegucigalpa', 14.07, -87.19, 1958, 'world_leader', 'Former Tegucigalpa mayor who won the 2025 election and took office in January 2026.'],
  ['Andrew Holness', 'Prime Minister', 'Jamaica', 'Jamaica Labour Party', 'Kingston', 18.02, -76.80, 1972, 'world_leader', 'Prime minister since 2016, re-elected in 2025.'],
  ['Claudia Sheinbaum', 'President', 'Mexico', 'Morena', 'Mexico City', 19.43, -99.13, 1962, 'world_leader', 'Climate scientist and Mexico\'s first female president, in office since 2024.'],
  ['Daniel Ortega', 'Co-President', 'Nicaragua', 'FSLN', 'Managua', 12.11, -86.24, 1945, 'world_leader', 'Sandinista leader in power since 2007; a 2025 reform made him co-president alongside his wife.'],
  ['Rosario Murillo', 'Co-President', 'Nicaragua', 'FSLN', 'Managua', 12.11, -86.24, 1951, 'world_leader', 'Vice-president turned co-president and Daniel Ortega\'s designated successor.'],
  ['José Raúl Mulino', 'President', 'Panama', 'Realizando Metas', 'Panama City', 8.98, -79.52, 1959, 'world_leader', 'President since 2024, elected as stand-in for the disqualified Ricardo Martinelli.'],
  ['Santiago Peña', 'President', 'Paraguay', 'Colorado Party', 'Asunción', -25.26, -57.58, 1978, 'world_leader', 'Economist and president since 2023.'],
  ['Terrance Drew', 'Prime Minister', 'Saint Kitts and Nevis', 'Labour Party', 'Basseterre', 17.30, -62.72, 1976, 'world_leader', 'Physician and prime minister since 2022.'],
  ['Philip J. Pierre', 'Prime Minister', 'Saint Lucia', 'Saint Lucia Labour Party', 'Castries', 14.01, -60.99, 1954, 'world_leader', 'Prime minister since 2021, re-elected in 2025.'],
  ['Godwin Friday', 'Prime Minister', 'Saint Vincent and the Grenadines', 'New Democratic Party', 'Kingstown', 13.16, -61.22, 1959, 'world_leader', 'Ended Ralph Gonsalves\'s 24-year rule by winning the 2025 election.'],
  ['Jennifer Geerlings-Simons', 'President', 'Suriname', 'National Democratic Party', 'Paramaribo', 5.85, -55.20, 1953, 'world_leader', 'Suriname\'s first female president, elected by parliament in 2025.'],
  ['Kamla Persad-Bissessar', 'Prime Minister', 'Trinidad and Tobago', 'United National Congress', 'Port of Spain', 10.65, -61.51, 1952, 'world_leader', 'Returned as prime minister in 2025 after a decade in opposition.'],
  ['Donald Trump', 'President', 'United States', 'Republican', 'Washington, D.C.', 38.91, -77.04, 1946, 'world_leader', '45th and 47th president of the United States, back in office since January 2025.'],
  ['JD Vance', 'Vice President', 'United States', 'Republican', 'Washington, D.C.', 38.91, -77.04, 1984, 'politician', 'Vice president of the United States since 2025; former senator from Ohio and venture capitalist.'],
  ['Yamandú Orsi', 'President', 'Uruguay', 'Broad Front', 'Montevideo', -34.90, -56.16, 1967, 'world_leader', 'History teacher and former governor, president since 2025.'],
  ['Delcy Rodríguez', 'Acting President', 'Venezuela', 'PSUV', 'Caracas', 10.48, -66.90, 1969, 'world_leader', 'Long-time Maduro lieutenant who assumed the presidency after his removal in January 2026.'],

  // ───────────── ASIA & MIDDLE EAST ─────────────
  ['Hibatullah Akhundzada', 'Supreme Leader', 'Afghanistan', 'Taliban', 'Kabul', 34.53, 69.17, 1961, 'world_leader', 'Reclusive cleric who has led the Taliban since 2016 and Afghanistan since 2021.'],
  ['Nikol Pashinyan', 'Prime Minister', 'Armenia', 'Civil Contract', 'Yerevan', 40.18, 44.51, 1975, 'world_leader', 'Came to power in the 2018 revolution; pursuing a peace deal with Azerbaijan.'],
  ['Ilham Aliyev', 'President', 'Azerbaijan', 'New Azerbaijan Party', 'Baku', 40.41, 49.87, 1961, 'world_leader', 'President since 2003, succeeding his father; retook Nagorno-Karabakh in 2023.'],
  ['Hamad bin Isa Al Khalifa', 'King', 'Bahrain', 'Monarchy', 'Manama', 26.23, 50.59, 1950, 'world_leader', 'Ruler of Bahrain since 1999 and king since 2002.'],
  ['Tarique Rahman', 'Prime Minister', 'Bangladesh', 'Bangladesh Nationalist Party', 'Dhaka', 23.81, 90.41, 1965, 'world_leader', 'BNP leader who returned from exile and became prime minister after the February 2026 election.'],
  ['Tshering Tobgay', 'Prime Minister', 'Bhutan', 'People\'s Democratic Party', 'Thimphu', 27.47, 89.64, 1965, 'world_leader', 'Prime minister since 2024; previously served 2013–2018.'],
  ['Hassanal Bolkiah', 'Sultan', 'Brunei', 'Monarchy', 'Bandar Seri Begawan', 4.94, 114.95, 1946, 'world_leader', 'Absolute monarch of Brunei since 1967, one of the world\'s longest-reigning.'],
  ['Hun Manet', 'Prime Minister', 'Cambodia', 'Cambodian People\'s Party', 'Phnom Penh', 11.56, 104.92, 1977, 'world_leader', 'West Point graduate who succeeded his father Hun Sen as prime minister in 2023.'],
  ['Xi Jinping', 'President and General Secretary', 'China', 'Chinese Communist Party', 'Beijing', 39.90, 116.40, 1953, 'world_leader', 'Paramount leader of China since 2012, serving an unprecedented third term.'],
  ['Nikos Christodoulides', 'President', 'Cyprus', 'Independent', 'Nicosia', 35.19, 33.38, 1973, 'world_leader', 'Former foreign minister, president of Cyprus since 2023.'],
  ['Irakli Kobakhidze', 'Prime Minister', 'Georgia', 'Georgian Dream', 'Tbilisi', 41.72, 44.79, 1978, 'world_leader', 'Prime minister since 2024 amid mass protests over the suspension of EU accession talks.'],
  ['Narendra Modi', 'Prime Minister', 'India', 'Bharatiya Janata Party', 'New Delhi', 28.61, 77.21, 1950, 'world_leader', 'Prime minister of India since 2014, now in a third term leading a coalition.'],
  ['Prabowo Subianto', 'President', 'Indonesia', 'Gerindra', 'Jakarta', -6.21, 106.85, 1951, 'world_leader', 'Former special-forces general elected president in 2024.'],
  ['Ali Khamenei', 'Supreme Leader', 'Iran', 'Islamic Republic', 'Tehran', 35.69, 51.39, 1939, 'world_leader', 'Supreme leader of Iran since 1989, the final authority on state and military matters.'],
  ['Masoud Pezeshkian', 'President', 'Iran', 'Reformist', 'Tehran', 35.69, 51.39, 1954, 'world_leader', 'Heart surgeon elected president in 2024 on a reformist ticket.'],
  ['Mohammed Shia al-Sudani', 'Prime Minister', 'Iraq', 'Coordination Framework', 'Baghdad', 33.32, 44.37, 1970, 'world_leader', 'Prime minister since 2022; his bloc won most seats in the November 2025 election.'],
  ['Benjamin Netanyahu', 'Prime Minister', 'Israel', 'Likud', 'Jerusalem', 31.77, 35.22, 1949, 'world_leader', 'Israel\'s longest-serving prime minister, in office again since 2022 and on trial for corruption.'],
  ['Sanae Takaichi', 'Prime Minister', 'Japan', 'Liberal Democratic Party', 'Tokyo', 35.68, 139.69, 1961, 'world_leader', 'Japan\'s first female prime minister, in office since October 2025.'],
  ['Abdullah II', 'King', 'Jordan', 'Monarchy', 'Amman', 31.95, 35.93, 1962, 'world_leader', 'King of Jordan since 1999.'],
  ['Kassym-Jomart Tokayev', 'President', 'Kazakhstan', 'Amanat', 'Astana', 51.17, 71.45, 1953, 'world_leader', 'President since 2019; consolidated power after the 2022 unrest.'],
  ['Mishal Al-Ahmad Al-Jaber Al-Sabah', 'Emir', 'Kuwait', 'Monarchy', 'Kuwait City', 29.38, 47.99, 1940, 'world_leader', 'Emir since 2023; suspended parliament in 2024.'],
  ['Sadyr Japarov', 'President', 'Kyrgyzstan', 'Independent', 'Bishkek', 42.87, 74.59, 1968, 'world_leader', 'Came to power after the 2020 unrest and expanded presidential authority.'],
  ['Thongloun Sisoulith', 'President', 'Laos', 'Lao People\'s Revolutionary Party', 'Vientiane', 17.97, 102.63, 1945, 'world_leader', 'Party general secretary and president of Laos since 2021.'],
  ['Joseph Aoun', 'President', 'Lebanon', 'Independent', 'Beirut', 33.89, 35.50, 1964, 'world_leader', 'Army commander elected president in January 2025 after a two-year vacancy.'],
  ['Nawaf Salam', 'Prime Minister', 'Lebanon', 'Independent', 'Beirut', 33.89, 35.50, 1953, 'world_leader', 'Former ICJ president appointed prime minister in 2025.'],
  ['Anwar Ibrahim', 'Prime Minister', 'Malaysia', 'People\'s Justice Party', 'Kuala Lumpur', 3.14, 101.69, 1947, 'world_leader', 'Prime minister since 2022 after decades as opposition leader and political prisoner.'],
  ['Mohamed Muizzu', 'President', 'Maldives', 'People\'s National Congress', 'Malé', 4.18, 73.51, 1978, 'world_leader', 'President since 2023, elected on an "India Out" platform.'],
  ['Ukhnaagiin Khürelsükh', 'President', 'Mongolia', 'Mongolian People\'s Party', 'Ulaanbaatar', 47.92, 106.92, 1968, 'world_leader', 'President of Mongolia since 2021.'],
  ['Min Aung Hlaing', 'President', 'Myanmar', 'Military', 'Naypyidaw', 19.76, 96.08, 1956, 'world_leader', 'Led the 2021 coup and was made president after the junta-run 2025–26 elections.'],
  ['Balendra Shah', 'Prime Minister', 'Nepal', 'Rastriya Swatantra Party', 'Kathmandu', 27.72, 85.32, 1990, 'world_leader', 'Rapper-turned-mayor of Kathmandu who became prime minister after the March 2026 election.'],
  ['Kim Jong Un', 'Supreme Leader', 'North Korea', 'Workers\' Party of Korea', 'Pyongyang', 39.02, 125.75, 1984, 'world_leader', 'Third-generation ruler of North Korea since 2011.'],
  ['Haitham bin Tariq', 'Sultan', 'Oman', 'Monarchy', 'Muscat', 23.59, 58.38, 1954, 'world_leader', 'Sultan of Oman since 2020.'],
  ['Shehbaz Sharif', 'Prime Minister', 'Pakistan', 'PML-N', 'Islamabad', 33.69, 73.04, 1951, 'world_leader', 'Prime minister since 2024, governing in the army\'s shadow.'],
  ['Asim Munir', 'Chief of Defence Forces', 'Pakistan', 'Pakistan Army', 'Rawalpindi', 33.60, 73.05, 1968, 'military', 'Field marshal widely seen as Pakistan\'s most powerful figure; elevated to a new supreme command post in 2025.'],
  ['Mahmoud Abbas', 'President of the Palestinian Authority', 'Palestine', 'Fatah', 'Ramallah', 31.90, 35.20, 1935, 'world_leader', 'President of the Palestinian Authority since 2005 without facing an election since.'],
  ['Ferdinand Marcos Jr.', 'President', 'Philippines', 'Partido Federal ng Pilipinas', 'Manila', 14.60, 120.98, 1957, 'world_leader', 'Son of the former dictator, president since 2022.'],
  ['Tamim bin Hamad Al Thani', 'Emir', 'Qatar', 'Monarchy', 'Doha', 25.29, 51.53, 1980, 'world_leader', 'Emir of Qatar since 2013, a key mediator in Gaza and Afghanistan talks.'],
  ['Mohammed bin Salman', 'Crown Prince and Prime Minister', 'Saudi Arabia', 'Monarchy', 'Riyadh', 24.71, 46.68, 1985, 'world_leader', 'De facto ruler of Saudi Arabia and architect of Vision 2030.'],
  ['Salman bin Abdulaziz', 'King', 'Saudi Arabia', 'Monarchy', 'Riyadh', 24.71, 46.68, 1935, 'world_leader', 'King of Saudi Arabia since 2015.'],
  ['Lawrence Wong', 'Prime Minister', 'Singapore', 'People\'s Action Party', 'Singapore', 1.35, 103.82, 1972, 'world_leader', 'Prime minister since 2024, Singapore\'s fourth.'],
  ['Lee Jae-myung', 'President', 'South Korea', 'Democratic Party', 'Seoul', 37.57, 126.98, 1963, 'world_leader', 'Elected in June 2025 after the impeachment of Yoon Suk Yeol.'],
  ['Anura Kumara Dissanayake', 'President', 'Sri Lanka', 'National People\'s Power', 'Colombo', 6.93, 79.86, 1968, 'world_leader', 'Marxist-leaning outsider elected president in 2024 after the economic collapse.'],
  ['Ahmed al-Sharaa', 'President', 'Syria', 'Transitional Government', 'Damascus', 33.51, 36.29, 1982, 'world_leader', 'Former HTS commander who toppled Assad in December 2024 and became transitional president.'],
  ['Lai Ching-te', 'President', 'Taiwan', 'Democratic Progressive Party', 'Taipei', 25.03, 121.57, 1959, 'world_leader', 'President of Taiwan since 2024.'],
  ['Emomali Rahmon', 'President', 'Tajikistan', 'People\'s Democratic Party', 'Dushanbe', 38.56, 68.79, 1952, 'world_leader', 'Has ruled Tajikistan since 1992.'],
  ['Anutin Charnvirakul', 'Prime Minister', 'Thailand', 'Bhumjaithai', 'Bangkok', 13.76, 100.50, 1966, 'world_leader', 'Became prime minister in 2025 and kept the job after the February 2026 election.'],
  ['Xanana Gusmão', 'Prime Minister', 'Timor-Leste', 'CNRT', 'Dili', -8.56, 125.58, 1946, 'world_leader', 'Independence hero and prime minister since 2023.'],
  ['Recep Tayyip Erdoğan', 'President', 'Turkey', 'AK Party', 'Ankara', 39.93, 32.86, 1954, 'world_leader', 'Has led Turkey since 2003, as prime minister and then president.'],
  ['Serdar Berdimuhamedow', 'President', 'Turkmenistan', 'Democratic Party', 'Ashgabat', 37.96, 58.33, 1981, 'world_leader', 'President since 2022, succeeding his father who retains a "national leader" role.'],
  ['Mohamed bin Zayed Al Nahyan', 'President', 'United Arab Emirates', 'Monarchy', 'Abu Dhabi', 24.45, 54.38, 1961, 'world_leader', 'President of the UAE and ruler of Abu Dhabi since 2022.'],
  ['Shavkat Mirziyoyev', 'President', 'Uzbekistan', 'Liberal Democratic Party', 'Tashkent', 41.30, 69.24, 1957, 'world_leader', 'President since 2016; a 2023 referendum reset his term limits.'],
  ['Tô Lâm', 'General Secretary of the Communist Party', 'Vietnam', 'Communist Party of Vietnam', 'Hanoi', 21.03, 105.85, 1957, 'world_leader', 'Former police minister who became Vietnam\'s top leader in 2024 and was reconfirmed in 2026.'],
  ['Rashad al-Alimi', 'Chairman of the Presidential Leadership Council', 'Yemen', 'General People\'s Congress', 'Aden', 12.79, 45.03, 1954, 'world_leader', 'Heads the internationally recognised government fighting the Houthis.'],

  // ───────────── EUROPE ─────────────
  ['Edi Rama', 'Prime Minister', 'Albania', 'Socialist Party', 'Tirana', 41.33, 19.82, 1964, 'world_leader', 'Painter-turned-politician, prime minister since 2013 and now in a fourth term.'],
  ['Xavier Espot', 'Head of Government', 'Andorra', 'Democrats for Andorra', 'Andorra la Vella', 42.51, 1.52, 1979, 'world_leader', 'Head of government of Andorra since 2019.'],
  ['Christian Stocker', 'Chancellor', 'Austria', 'Austrian People\'s Party', 'Vienna', 48.21, 16.37, 1960, 'world_leader', 'Chancellor since 2025, leading a three-party coalition that kept the far-right FPÖ out of power.'],
  ['Alexander Lukashenko', 'President', 'Belarus', 'Independent', 'Minsk', 53.90, 27.57, 1954, 'world_leader', 'Has ruled Belarus since 1994; claimed a seventh term in 2025.'],
  ['Bart De Wever', 'Prime Minister', 'Belgium', 'New Flemish Alliance', 'Brussels', 50.85, 4.35, 1970, 'world_leader', 'Flemish nationalist who became Belgian prime minister in 2025.'],
  ['Željko Komšić', 'Chairman of the Presidency', 'Bosnia and Herzegovina', 'Democratic Front', 'Sarajevo', 43.86, 18.41, 1964, 'world_leader', 'Croat member of the tripartite presidency, holding the rotating chair in 2026.'],
  ['Iliana Iotova', 'President', 'Bulgaria', 'Independent', 'Sofia', 42.70, 23.32, 1964, 'world_leader', 'Became president in 2026 after Rumen Radev resigned to enter party politics.'],
  ['Andrej Plenković', 'Prime Minister', 'Croatia', 'HDZ', 'Zagreb', 45.81, 15.98, 1970, 'world_leader', 'Prime minister since 2016, Croatia\'s longest-serving.'],
  ['Andrej Babiš', 'Prime Minister', 'Czech Republic', 'ANO', 'Prague', 50.08, 14.44, 1954, 'world_leader', 'Billionaire populist who returned as prime minister after winning the 2025 election.'],
  ['Mette Frederiksen', 'Prime Minister', 'Denmark', 'Social Democrats', 'Copenhagen', 55.68, 12.57, 1977, 'world_leader', 'Prime minister since 2019; led Denmark through the Greenland crisis with Washington.'],
  ['Kristen Michal', 'Prime Minister', 'Estonia', 'Reform Party', 'Tallinn', 59.44, 24.75, 1975, 'world_leader', 'Prime minister since 2024.'],
  ['Petteri Orpo', 'Prime Minister', 'Finland', 'National Coalition Party', 'Helsinki', 60.17, 24.94, 1969, 'world_leader', 'Prime minister since 2023, leading a right-wing coalition.'],
  ['Emmanuel Macron', 'President', 'France', 'Renaissance', 'Paris', 48.86, 2.35, 1977, 'world_leader', 'President since 2017, governing without a majority since the 2024 snap election.'],
  ['Sébastien Lecornu', 'Prime Minister', 'France', 'Renaissance', 'Paris', 48.86, 2.35, 1986, 'world_leader', 'Macron loyalist appointed prime minister in 2025 after successive government collapses.'],
  ['Friedrich Merz', 'Chancellor', 'Germany', 'CDU', 'Berlin', 52.52, 13.41, 1955, 'world_leader', 'Chancellor since May 2025, leading a CDU–SPD coalition.'],
  ['Kyriakos Mitsotakis', 'Prime Minister', 'Greece', 'New Democracy', 'Athens', 37.98, 23.73, 1968, 'world_leader', 'Prime minister since 2019, in a second term since 2023.'],
  ['Péter Magyar', 'Prime Minister', 'Hungary', 'Tisza', 'Budapest', 47.50, 19.04, 1981, 'world_leader', 'Former Fidesz insider whose Tisza party unseated Viktor Orbán in the April 2026 election.'],
  ['Kristrún Frostadóttir', 'Prime Minister', 'Iceland', 'Social Democratic Alliance', 'Reykjavík', 64.15, -21.94, 1988, 'world_leader', 'Economist who became Iceland\'s youngest prime minister in 2024.'],
  ['Micheál Martin', 'Taoiseach', 'Ireland', 'Fianna Fáil', 'Dublin', 53.35, -6.26, 1960, 'world_leader', 'Taoiseach again since 2025 under a rotating coalition arrangement.'],
  ['Catherine Connolly', 'President', 'Ireland', 'Independent', 'Dublin', 53.35, -6.26, 1957, 'world_leader', 'Left-wing independent elected president of Ireland in 2025.'],
  ['Giorgia Meloni', 'Prime Minister', 'Italy', 'Brothers of Italy', 'Rome', 41.90, 12.50, 1977, 'world_leader', 'Italy\'s first female prime minister, in office since 2022.'],
  ['Albin Kurti', 'Prime Minister', 'Kosovo', 'Vetëvendosje', 'Pristina', 42.66, 21.17, 1975, 'world_leader', 'Prime minister of Kosovo, leading after a prolonged 2025 government-formation standoff.'],
  ['Evika Siliņa', 'Prime Minister', 'Latvia', 'New Unity', 'Riga', 56.95, 24.11, 1975, 'world_leader', 'Prime minister since 2023.'],
  ['Brigitte Haas', 'Prime Minister', 'Liechtenstein', 'Progressive Citizens\' Party', 'Vaduz', 47.14, 9.52, 1967, 'world_leader', 'Liechtenstein\'s first female head of government, since 2025.'],
  ['Inga Ruginienė', 'Prime Minister', 'Lithuania', 'Social Democratic Party', 'Vilnius', 54.69, 25.28, 1981, 'world_leader', 'Former trade-union leader, prime minister since 2025.'],
  ['Luc Frieden', 'Prime Minister', 'Luxembourg', 'Christian Social People\'s Party', 'Luxembourg', 49.61, 6.13, 1963, 'world_leader', 'Prime minister since 2023.'],
  ['Robert Abela', 'Prime Minister', 'Malta', 'Labour Party', 'Valletta', 35.90, 14.51, 1977, 'world_leader', 'Prime minister since 2020.'],
  ['Maia Sandu', 'President', 'Moldova', 'Party of Action and Solidarity', 'Chișinău', 47.01, 28.86, 1972, 'world_leader', 'Pro-EU president since 2020, re-elected in 2024 amid Russian interference claims.'],
  ['Albert II', 'Prince', 'Monaco', 'Monarchy', 'Monaco', 43.73, 7.42, 1958, 'world_leader', 'Sovereign prince of Monaco since 2005.'],
  ['Milojko Spajić', 'Prime Minister', 'Montenegro', 'Europe Now!', 'Podgorica', 42.44, 19.26, 1987, 'world_leader', 'Prime minister since 2023.'],
  ['Rob Jetten', 'Prime Minister', 'Netherlands', 'D66', 'Amsterdam', 52.37, 4.90, 1987, 'world_leader', 'D66 leader who became prime minister after his party\'s surge in the October 2025 election.'],
  ['Hristijan Mickoski', 'Prime Minister', 'North Macedonia', 'VMRO-DPMNE', 'Skopje', 42.00, 21.43, 1977, 'world_leader', 'Prime minister since 2024.'],
  ['Jonas Gahr Støre', 'Prime Minister', 'Norway', 'Labour Party', 'Oslo', 59.91, 10.75, 1960, 'world_leader', 'Prime minister since 2021, re-elected in September 2025.'],
  ['Donald Tusk', 'Prime Minister', 'Poland', 'Civic Platform', 'Warsaw', 52.23, 21.01, 1957, 'world_leader', 'Prime minister since 2023, in cohabitation with a hostile president.'],
  ['Karol Nawrocki', 'President', 'Poland', 'Independent', 'Warsaw', 52.23, 21.01, 1983, 'world_leader', 'Historian backed by Law and Justice, president since August 2025.'],
  ['Luís Montenegro', 'Prime Minister', 'Portugal', 'Social Democratic Party', 'Lisbon', 38.72, -9.14, 1973, 'world_leader', 'Prime minister since 2024, strengthened by the May 2025 snap election.'],
  ['António José Seguro', 'President', 'Portugal', 'Socialist Party', 'Lisbon', 38.72, -9.14, 1962, 'world_leader', 'Former Socialist leader who won the 2026 presidential runoff against André Ventura.'],
  ['Nicușor Dan', 'President', 'Romania', 'Independent', 'Bucharest', 44.43, 26.10, 1969, 'world_leader', 'Mathematician and Bucharest mayor elected president in the rerun 2025 election.'],
  ['Ilie Bolojan', 'Prime Minister', 'Romania', 'National Liberal Party', 'Bucharest', 44.43, 26.10, 1969, 'world_leader', 'Prime minister since 2025, pushing austerity to close a record deficit.'],
  ['Vladimir Putin', 'President', 'Russia', 'United Russia', 'Moscow', 55.76, 37.62, 1952, 'world_leader', 'Has ruled Russia since 1999; launched the full-scale invasion of Ukraine in 2022.'],
  ['Aleksandar Vučić', 'President', 'Serbia', 'Serbian Progressive Party', 'Belgrade', 44.79, 20.45, 1970, 'world_leader', 'President since 2017, facing the largest protests of his rule since 2024.'],
  ['Robert Fico', 'Prime Minister', 'Slovakia', 'Smer', 'Bratislava', 48.15, 17.11, 1964, 'world_leader', 'Four-time prime minister, back in office since 2023 and survivor of a 2024 assassination attempt.'],
  ['Janez Janša', 'Prime Minister', 'Slovenia', 'Slovenian Democratic Party', 'Ljubljana', 46.06, 14.51, 1958, 'world_leader', 'Returned as prime minister after his party came first in the March 2026 election.'],
  ['Pedro Sánchez', 'Prime Minister', 'Spain', 'PSOE', 'Madrid', 40.42, -3.70, 1972, 'world_leader', 'Prime minister since 2018, governing a fragile minority coalition.'],
  ['Ulf Kristersson', 'Prime Minister', 'Sweden', 'Moderate Party', 'Stockholm', 59.33, 18.07, 1963, 'world_leader', 'Prime minister since 2022 with Sweden Democrats support; faced election in September 2026.'],
  ['Guy Parmelin', 'President of the Swiss Confederation', 'Switzerland', 'Swiss People\'s Party', 'Bern', 46.95, 7.45, 1959, 'world_leader', 'Economy minister holding the rotating Swiss presidency for 2026.'],
  ['Volodymyr Zelensky', 'President', 'Ukraine', 'Servant of the People', 'Kyiv', 50.45, 30.52, 1978, 'world_leader', 'Comedian-turned-president since 2019, leading Ukraine through Russia\'s invasion.'],
  ['Keir Starmer', 'Prime Minister', 'United Kingdom', 'Labour', 'London', 51.51, -0.13, 1962, 'world_leader', 'Prime minister since July 2024 after Labour\'s landslide.'],
  ['Charles III', 'King', 'United Kingdom', 'Monarchy', 'London', 51.51, -0.13, 1948, 'world_leader', 'King of the United Kingdom and 14 other realms since 2022.'],
  ['Leo XIV', 'Pope', 'Vatican City', 'Catholic Church', 'Vatican City', 41.90, 12.45, 1955, 'religious', 'First American pope, elected in May 2025; head of the Catholic Church and Vatican City State.'],

  // ───────────── OCEANIA ─────────────
  ['Anthony Albanese', 'Prime Minister', 'Australia', 'Labor', 'Canberra', -35.28, 149.13, 1963, 'world_leader', 'Prime minister since 2022, re-elected in a 2025 landslide.'],
  ['Sitiveni Rabuka', 'Prime Minister', 'Fiji', 'People\'s Alliance', 'Suva', -18.14, 178.44, 1948, 'world_leader', 'Former coup leader, prime minister again since 2022.'],
  ['Taneti Maamau', 'President', 'Kiribati', 'Tobwaan Kiribati Party', 'Tarawa', 1.45, 173.03, 1960, 'world_leader', 'President since 2016.'],
  ['Hilda Heine', 'President', 'Marshall Islands', 'Independent', 'Majuro', 7.09, 171.38, 1951, 'world_leader', 'President since 2024; previously served 2016–2020.'],
  ['Wesley Simina', 'President', 'Micronesia', 'Independent', 'Palikir', 6.92, 158.16, 1961, 'world_leader', 'President since 2023.'],
  ['David Adeang', 'President', 'Nauru', 'Independent', 'Yaren', -0.55, 166.92, 1969, 'world_leader', 'President since 2023.'],
  ['Christopher Luxon', 'Prime Minister', 'New Zealand', 'National Party', 'Wellington', -41.29, 174.78, 1970, 'world_leader', 'Former Air New Zealand chief, prime minister since 2023.'],
  ['Surangel Whipps Jr.', 'President', 'Palau', 'Independent', 'Ngerulmud', 7.50, 134.62, 1968, 'world_leader', 'President since 2021, re-elected in 2024.'],
  ['James Marape', 'Prime Minister', 'Papua New Guinea', 'Pangu Pati', 'Port Moresby', -9.44, 147.18, 1971, 'world_leader', 'Prime minister since 2019.'],
  ['Laʻauli Leuatea Schmidt', 'Prime Minister', 'Samoa', 'FAST', 'Apia', -13.83, -171.76, 1963, 'world_leader', 'Became prime minister after the August 2025 snap election.'],
  ['Jeremiah Manele', 'Prime Minister', 'Solomon Islands', 'OUR Party', 'Honiara', -9.43, 159.95, 1968, 'world_leader', 'Prime minister since 2024.'],
  ['ʻAisake Eke', 'Prime Minister', 'Tonga', 'Independent', 'Nukuʻalofa', -21.14, -175.20, 1959, 'world_leader', 'Economist and prime minister since January 2025.'],
  ['Feleti Teo', 'Prime Minister', 'Tuvalu', 'Independent', 'Funafuti', -8.52, 179.20, 1962, 'world_leader', 'Prime minister since 2024.'],
  ['Jotham Napat', 'Prime Minister', 'Vanuatu', 'Leaders Party', 'Port Vila', -17.73, 168.32, 1967, 'world_leader', 'Prime minister since 2025.'],

  // ───────────── INTERNATIONAL INSTITUTIONS ─────────────
  ['António Guterres', 'Secretary-General', 'United Nations', 'United Nations', 'New York', 40.75, -73.97, 1949, 'international', 'UN secretary-general since 2017; former prime minister of Portugal.'],
  ['Ursula von der Leyen', 'President of the European Commission', 'European Union', 'European People\'s Party', 'Brussels', 50.85, 4.35, 1958, 'international', 'Head of the EU executive since 2019, serving a second term.'],
  ['Mark Rutte', 'Secretary General', 'NATO', 'NATO', 'Brussels', 50.85, 4.35, 1967, 'international', 'Former Dutch prime minister leading NATO since 2024.'],
  ['Kristalina Georgieva', 'Managing Director', 'International Monetary Fund', 'IMF', 'Washington, D.C.', 38.90, -77.04, 1953, 'international', 'Bulgarian economist leading the IMF since 2019.'],
  ['Ajay Banga', 'President', 'World Bank', 'World Bank', 'Washington, D.C.', 38.90, -77.04, 1959, 'international', 'Former Mastercard chief, World Bank president since 2023.'],
  ['Tedros Adhanom Ghebreyesus', 'Director-General', 'World Health Organization', 'WHO', 'Geneva', 46.20, 6.14, 1965, 'international', 'Head of the WHO since 2017, through the pandemic and the US withdrawal.'],
  ['Christine Lagarde', 'President', 'European Central Bank', 'ECB', 'Frankfurt', 50.11, 8.68, 1956, 'international', 'ECB president since 2019; previously ran the IMF.'],
  ['Gianni Infantino', 'President', 'FIFA', 'FIFA', 'Zurich', 47.38, 8.54, 1970, 'international', 'Head of world football\'s governing body since 2016.'],
  ['Kirsty Coventry', 'President', 'International Olympic Committee', 'IOC', 'Lausanne', 46.52, 6.63, 1983, 'international', 'Zimbabwean Olympic champion, IOC president since 2025 and the first woman in the post.'],

  // ───────────── BUSINESS ─────────────
  ['Elon Musk', 'CEO of Tesla, SpaceX and xAI', 'United States', 'Tesla / SpaceX / xAI', 'Austin', 30.27, -97.74, 1971, 'business', 'World\'s richest person; owner of X and a former head of the Trump administration\'s DOGE.'],
  ['Bill Gates', 'Chair of the Gates Foundation', 'United States', 'Gates Foundation', 'Seattle', 47.61, -122.33, 1955, 'business', 'Microsoft co-founder who now runs the world\'s largest private philanthropic foundation.'],
  ['Jeff Bezos', 'Executive Chairman of Amazon', 'United States', 'Amazon / Blue Origin', 'Seattle', 47.61, -122.33, 1964, 'business', 'Amazon founder, owner of the Washington Post and Blue Origin.'],
  ['Mark Zuckerberg', 'CEO of Meta', 'United States', 'Meta', 'Menlo Park', 37.45, -122.18, 1984, 'business', 'Founder and controlling shareholder of Facebook, Instagram and WhatsApp.'],
  ['Tim Cook', 'CEO of Apple', 'United States', 'Apple', 'Cupertino', 37.32, -122.03, 1960, 'business', 'Has run Apple since 2011.'],
  ['Sundar Pichai', 'CEO of Alphabet and Google', 'United States', 'Alphabet', 'Mountain View', 37.39, -122.08, 1972, 'business', 'Head of Google since 2015 and Alphabet since 2019.'],
  ['Satya Nadella', 'CEO of Microsoft', 'United States', 'Microsoft', 'Redmond', 47.67, -122.12, 1967, 'business', 'Has led Microsoft since 2014 and its deep partnership with OpenAI.'],
  ['Sam Altman', 'CEO of OpenAI', 'United States', 'OpenAI', 'San Francisco', 37.77, -122.42, 1985, 'business', 'Runs OpenAI, maker of ChatGPT; briefly ousted and reinstated in 2023.'],
  ['Jensen Huang', 'CEO of Nvidia', 'United States', 'Nvidia', 'Santa Clara', 37.35, -121.96, 1963, 'business', 'Co-founder of Nvidia, the chipmaker at the centre of the AI boom.'],
  ['Dario Amodei', 'CEO of Anthropic', 'United States', 'Anthropic', 'San Francisco', 37.77, -122.42, 1983, 'business', 'Co-founder of Anthropic, the AI company behind Claude.'],
  ['Warren Buffett', 'Chairman of Berkshire Hathaway', 'United States', 'Berkshire Hathaway', 'Omaha', 41.26, -95.94, 1930, 'business', 'The "Oracle of Omaha", who handed the CEO role to Greg Abel at the end of 2025.'],
  ['Larry Ellison', 'Chairman of Oracle', 'United States', 'Oracle', 'Austin', 30.27, -97.74, 1944, 'business', 'Oracle co-founder and a key investor in the TikTok US deal.'],
  ['Larry Page', 'Co-founder of Google', 'United States', 'Alphabet', 'Palo Alto', 37.44, -122.14, 1973, 'business', 'Google co-founder and Alphabet controlling shareholder.'],
  ['Sergey Brin', 'Co-founder of Google', 'United States', 'Alphabet', 'Palo Alto', 37.44, -122.14, 1973, 'business', 'Google co-founder who returned to hands-on work on Gemini.'],
  ['Andy Jassy', 'CEO of Amazon', 'United States', 'Amazon', 'Seattle', 47.61, -122.33, 1968, 'business', 'Amazon chief executive since 2021.'],
  ['Alex Karp', 'CEO of Palantir', 'United States', 'Palantir', 'Denver', 39.74, -104.99, 1967, 'business', 'Co-founder of the defence and surveillance data firm Palantir.'],
  ['Peter Thiel', 'Chairman of Palantir', 'United States', 'Palantir / Founders Fund', 'Los Angeles', 34.05, -118.24, 1967, 'business', 'PayPal co-founder, Palantir chairman and major right-wing political donor.'],
  ['Jamie Dimon', 'CEO of JPMorgan Chase', 'United States', 'JPMorgan Chase', 'New York', 40.71, -74.01, 1956, 'business', 'Has run the largest US bank since 2005.'],
  ['Larry Fink', 'CEO of BlackRock', 'United States', 'BlackRock', 'New York', 40.71, -74.01, 1952, 'business', 'Heads the world\'s largest asset manager.'],
  ['Michael Bloomberg', 'Founder of Bloomberg L.P.', 'United States', 'Bloomberg L.P.', 'New York', 40.71, -74.01, 1942, 'business', 'Media billionaire and former mayor of New York.'],
  ['Marc Benioff', 'CEO of Salesforce', 'United States', 'Salesforce', 'San Francisco', 37.77, -122.42, 1964, 'business', 'Salesforce founder and owner of Time magazine.'],
  ['Michael Dell', 'CEO of Dell Technologies', 'United States', 'Dell', 'Round Rock', 30.51, -97.68, 1965, 'business', 'Founder and chief executive of Dell.'],
  ['Mark Cuban', 'Investor', 'United States', 'Cost Plus Drugs', 'Dallas', 32.78, -96.80, 1958, 'business', 'Billionaire investor, former Mavericks owner and Cost Plus Drugs founder.'],
  ['Ray Dalio', 'Founder of Bridgewater Associates', 'United States', 'Bridgewater', 'Westport', 41.14, -73.36, 1949, 'business', 'Founder of the world\'s largest hedge fund.'],
  ['Rupert Murdoch', 'Chairman Emeritus of News Corp and Fox', 'United States', 'News Corp / Fox', 'New York', 40.71, -74.01, 1931, 'media', 'Built a global media empire spanning Fox News, the Wall Street Journal and the Sun.'],
  ['Lachlan Murdoch', 'CEO of Fox Corporation', 'United States', 'Fox Corporation', 'New York', 40.71, -74.01, 1971, 'media', 'Took control of the Murdoch empire after the 2025 family trust settlement.'],
  ['Bernard Arnault', 'CEO of LVMH', 'France', 'LVMH', 'Paris', 48.86, 2.35, 1949, 'business', 'Chairman of the world\'s largest luxury group.'],
  ['Mukesh Ambani', 'Chairman of Reliance Industries', 'India', 'Reliance Industries', 'Mumbai', 19.08, 72.88, 1957, 'business', 'India\'s richest man, running the Reliance conglomerate.'],
  ['Gautam Adani', 'Chairman of Adani Group', 'India', 'Adani Group', 'Ahmedabad', 23.02, 72.57, 1962, 'business', 'Infrastructure tycoon indicted in the US on bribery charges in 2024.'],
  ['Jack Ma', 'Co-founder of Alibaba', 'China', 'Alibaba', 'Hangzhou', 30.27, 120.15, 1964, 'business', 'Alibaba founder who vanished from public view after criticising regulators in 2020.'],
  ['Zhang Yiming', 'Founder of ByteDance', 'China', 'ByteDance', 'Beijing', 39.90, 116.40, 1983, 'business', 'Founder of TikTok\'s parent company and China\'s richest person.'],
  ['Pony Ma', 'CEO of Tencent', 'China', 'Tencent', 'Shenzhen', 22.54, 114.06, 1971, 'business', 'Founder of Tencent, owner of WeChat.'],
  ['Carlos Slim', 'Chairman of Grupo Carso', 'Mexico', 'Grupo Carso / América Movil', 'Mexico City', 19.43, -99.13, 1940, 'business', 'Telecoms magnate and Latin America\'s richest man.'],

  // ───────────── MEDIA & INFLUENCE ─────────────
  ['Joe Rogan', 'Podcast Host', 'United States', 'The Joe Rogan Experience', 'Austin', 30.27, -97.74, 1967, 'media', 'Host of the most-listened-to podcast in the world.'],
  ['Tucker Carlson', 'Broadcaster', 'United States', 'Tucker Carlson Network', 'Washington, D.C.', 38.91, -77.04, 1969, 'media', 'Former Fox News host now running his own network.'],
  ['Jimmy Donaldson', 'YouTuber', 'United States', 'MrBeast', 'Greenville', 35.61, -77.37, 1998, 'media', 'Known as MrBeast; the most-subscribed creator on YouTube.'],
  ['Oprah Winfrey', 'Media Executive', 'United States', 'Harpo Productions', 'Chicago', 41.88, -87.63, 1954, 'media', 'Talk-show pioneer and one of the most influential figures in American media.'],
  ['Piers Morgan', 'Broadcaster', 'United Kingdom', 'Piers Morgan Uncensored', 'London', 51.51, -0.13, 1965, 'media', 'Former tabloid editor and YouTube talk-show host.'],
  ['Ben Shapiro', 'Commentator', 'United States', 'The Daily Wire', 'Nashville', 36.16, -86.78, 1984, 'media', 'Co-founder of the Daily Wire and conservative podcast host.'],

  // ───────────── JUDICIARY ─────────────
  ['John Roberts', 'Chief Justice of the United States', 'United States', 'Supreme Court', 'Washington, D.C.', 38.89, -77.00, 1955, 'judiciary', 'Chief justice since 2005.'],
  ['Clarence Thomas', 'Associate Justice of the Supreme Court', 'United States', 'Supreme Court', 'Washington, D.C.', 38.89, -77.00, 1948, 'judiciary', 'Longest-serving current justice; subject of undisclosed-gifts controversies.'],
  ['Samuel Alito', 'Associate Justice of the Supreme Court', 'United States', 'Supreme Court', 'Washington, D.C.', 38.89, -77.00, 1950, 'judiciary', 'Author of the decision overturning Roe v. Wade.'],
  ['Sonia Sotomayor', 'Associate Justice of the Supreme Court', 'United States', 'Supreme Court', 'Washington, D.C.', 38.89, -77.00, 1954, 'judiciary', 'Senior member of the court\'s liberal wing.'],
  ['Brett Kavanaugh', 'Associate Justice of the Supreme Court', 'United States', 'Supreme Court', 'Washington, D.C.', 38.89, -77.00, 1965, 'judiciary', 'Confirmed in 2018 after contentious hearings.'],
  ['Amy Coney Barrett', 'Associate Justice of the Supreme Court', 'United States', 'Supreme Court', 'Washington, D.C.', 38.89, -77.00, 1972, 'judiciary', 'Confirmed in 2020, cementing the court\'s conservative majority.'],
  ['Richard Wagner', 'Chief Justice of Canada', 'Canada', 'Supreme Court of Canada', 'Ottawa', 45.42, -75.70, 1957, 'judiciary', 'Chief justice of Canada since 2017.'],
  ['Robert Reed', 'President of the Supreme Court', 'United Kingdom', 'UK Supreme Court', 'London', 51.50, -0.13, 1956, 'judiciary', 'Lord Reed, president of the UK Supreme Court since 2020.'],
  ['Yuji Iwasawa', 'President of the International Court of Justice', 'International Court of Justice', 'ICJ', 'The Hague', 52.08, 4.30, 1954, 'judiciary', 'Japanese jurist presiding over the UN\'s top court since 2025.'],

  // ───────────── RELIGIOUS ─────────────
  ['Tenzin Gyatso', '14th Dalai Lama', 'Tibet', 'Tibetan Buddhism', 'Dharamshala', 32.22, 76.32, 1935, 'religious', 'Spiritual leader of Tibetan Buddhism, in exile in India since 1959.'],
  ['Ali al-Sistani', 'Grand Ayatollah', 'Iraq', 'Shia Islam', 'Najaf', 32.03, 44.33, 1930, 'religious', 'The most influential Shia cleric in Iraq.'],
  ['Kirill', 'Patriarch of Moscow and all Rus\'', 'Russia', 'Russian Orthodox Church', 'Moscow', 55.76, 37.62, 1946, 'religious', 'Head of the Russian Orthodox Church and vocal supporter of the war in Ukraine.'],
  ['Bartholomew I', 'Ecumenical Patriarch of Constantinople', 'Turkey', 'Eastern Orthodox Church', 'Istanbul', 41.01, 28.98, 1940, 'religious', 'First among equals of the Eastern Orthodox bishops since 1991.'],
  ['Ahmed el-Tayeb', 'Grand Imam of al-Azhar', 'Egypt', 'Sunni Islam', 'Cairo', 30.04, 31.24, 1946, 'religious', 'Head of al-Azhar, the foremost seat of Sunni learning.'],

  // ───────────── OTHER PROMINENT POLITICIANS ─────────────
  ['Marco Rubio', 'Secretary of State', 'United States', 'Republican', 'Washington, D.C.', 38.91, -77.04, 1971, 'politician', 'US secretary of state and national security adviser under Trump.'],
  ['Pete Hegseth', 'Secretary of War', 'United States', 'Republican', 'Washington, D.C.', 38.91, -77.04, 1980, 'politician', 'Former Fox host running the renamed Department of War.'],
  ['Robert F. Kennedy Jr.', 'Secretary of Health and Human Services', 'United States', 'Republican', 'Washington, D.C.', 38.91, -77.04, 1954, 'politician', 'Vaccine sceptic overseeing US health policy since 2025.'],
  ['Gavin Newsom', 'Governor of California', 'United States', 'Democratic', 'Sacramento', 38.58, -121.49, 1967, 'politician', 'Governor of California and a leading Democratic contender for 2028.'],
  ['Nigel Farage', 'Leader of Reform UK', 'United Kingdom', 'Reform UK', 'London', 51.51, -0.13, 1964, 'politician', 'Brexit architect whose Reform UK leads national polls.'],
  ['Marine Le Pen', 'Leader of the National Rally group', 'France', 'National Rally', 'Paris', 48.86, 2.35, 1968, 'politician', 'Far-right leader barred from office in 2025 pending appeal of an embezzlement conviction.'],
  ['Jordan Bardella', 'President of the National Rally', 'France', 'National Rally', 'Paris', 48.86, 2.35, 1995, 'politician', 'Le Pen\'s protégé and presumptive 2027 presidential candidate.'],
  ['Alice Weidel', 'Co-leader of the AfD', 'Germany', 'Alternative for Germany', 'Berlin', 52.52, 13.41, 1979, 'politician', 'Leads Germany\'s largest opposition party.'],
  ['Viktor Orbán', 'Leader of Fidesz', 'Hungary', 'Fidesz', 'Budapest', 47.50, 19.04, 1963, 'politician', 'Prime minister 2010–2026, ousted in the April 2026 election.'],
  ['Rahul Gandhi', 'Leader of the Opposition', 'India', 'Indian National Congress', 'New Delhi', 28.61, 77.21, 1970, 'politician', 'Congress leader and leader of the opposition in the Lok Sabha.'],
]

// Prominence: drives the "main view" (world leaders + top 50 figures) and default sort.
// World leaders default to 50; the most consequential are lifted above that.
export const PROMINENCE: Record<string, number> = {
  // Heads of state / government
  'Donald Trump': 100, 'Xi Jinping': 99, 'Vladimir Putin': 98, 'Narendra Modi': 96, 'Keir Starmer': 92,
  'Emmanuel Macron': 92, 'Friedrich Merz': 92, 'Benjamin Netanyahu': 91, 'Mohammed bin Salman': 91,
  'Volodymyr Zelensky': 91, 'Ursula von der Leyen': 90, 'Giorgia Meloni': 88, 'Sanae Takaichi': 88,
  'Luiz Inácio Lula da Silva': 88, 'Claudia Sheinbaum': 87, 'Recep Tayyip Erdoğan': 87, 'Ali Khamenei': 87,
  'Kim Jong Un': 86, 'Mark Carney': 86, 'Javier Milei': 85, 'Lee Jae-myung': 84, 'Anthony Albanese': 84,
  'Prabowo Subianto': 82, 'Cyril Ramaphosa': 82, 'Pedro Sánchez': 82, 'Donald Tusk': 82, 'Abdel Fattah el-Sisi': 80,
  'Bola Tinubu': 80, 'Mohamed bin Zayed Al Nahyan': 80, 'Tamim bin Hamad Al Thani': 78, 'Ahmed al-Sharaa': 78,
  'Shehbaz Sharif': 76, 'Nayib Bukele': 76, 'Viktor Orbán': 70, 'Péter Magyar': 76, 'Lai Ching-te': 76,
  'JD Vance': 85, 'Mark Rutte': 75, 'António Guterres': 74, 'Charles III': 74, 'Leo XIV': 90,
  // Business
  'Elon Musk': 97, 'Mark Zuckerberg': 89, 'Jeff Bezos': 88, 'Bill Gates': 86, 'Sam Altman': 86, 'Jensen Huang': 85,
  'Rupert Murdoch': 84, 'Larry Ellison': 82, 'Satya Nadella': 80, 'Sundar Pichai': 80, 'Tim Cook': 80,
  'Peter Thiel': 79, 'Jamie Dimon': 78, 'Larry Fink': 77, 'Warren Buffett': 77, 'Lachlan Murdoch': 76,
  'Bernard Arnault': 74, 'Mukesh Ambani': 74, 'Dario Amodei': 73, 'Alex Karp': 72, 'Michael Bloomberg': 71,
  'Zhang Yiming': 70, 'Gautam Adani': 69, 'Larry Page': 68, 'Sergey Brin': 68, 'Andy Jassy': 66, 'Pony Ma': 65,
  'Jack Ma': 64, 'Marc Benioff': 60, 'Michael Dell': 58, 'Carlos Slim': 62, 'Mark Cuban': 55, 'Ray Dalio': 52,
  // Media
  'Joe Rogan': 78, 'Tucker Carlson': 72, 'Jimmy Donaldson': 66, 'Oprah Winfrey': 64, 'Ben Shapiro': 58, 'Piers Morgan': 54,
  // Judiciary / religious / international / military
  'John Roberts': 80, 'Clarence Thomas': 70, 'Samuel Alito': 68, 'Amy Coney Barrett': 66, 'Brett Kavanaugh': 64,
  'Sonia Sotomayor': 62, 'Richard Wagner': 40, 'Robert Reed': 42, 'Yuji Iwasawa': 44,
  'Tenzin Gyatso': 66, 'Ali al-Sistani': 60, 'Kirill': 62, 'Bartholomew I': 48, 'Ahmed el-Tayeb': 50,
  'Christine Lagarde': 72, 'Kristalina Georgieva': 68, 'Tedros Adhanom Ghebreyesus': 66, 'Ajay Banga': 60,
  'Gianni Infantino': 62, 'Kirsty Coventry': 50, 'Asim Munir': 70,
  // Other politicians
  'Marco Rubio': 82, 'Pete Hegseth': 76, 'Robert F. Kennedy Jr.': 76, 'Gavin Newsom': 74, 'Nigel Farage': 74,
  'Marine Le Pen': 70, 'Jordan Bardella': 70, 'Alice Weidel': 68, 'Rahul Gandhi': 62, 'Pierre Poilievre': 60,
}
